### ISSUE TITLE
中文博客列表导航合作申请

### ISSUE THREAD

**Issue by linlinzzo** [saveweb/rss-list#4]
我个人认为我们分别维护两个功能差不多的列表有点浪费精力，所以我向你们提出合作申请。这项合作申请最早在今年高考之后才能得以施行，现在开这个 issue 是要让双方就粗略的方案达成共识。

我代表我自己发表一些看法：
1. 双方合作的范围目前仅限于博客列表，但不排除我们还可以在其它方面进行合作。
2. 我个人认为列表由双方原来负责维护列表的人员共同维护，中文博客全订阅使用我们中文博客列表导航项目提供的 opml 接口。

在此艾特双方的人员。
@yzqzss @Mabbs @gledos @renbaoshuo @lijiajunljj 
@OhYee @MYXXTS @zkeq

**Comment by cronfox** [comment]
不知道说什么为好

但保留自有opml接口肯定没有坏处(

**Comment by linlinzzo** [comment]
> 不知道说什么为好
> 
> 但保留自有opml接口肯定没有坏处(

之后双方都可以对列表进行备份，中文博客列表导航现在就在弄。https://github.com/zh-blogs/zh-blog-database

**Comment by ghost** [comment]
下面是我个人的观点：

中文博客并不是每个都在 HTML 中声明自己的博客是中文，即在 HTML 中的标签内写上 lang="zh"。如果按照这个标准来执行的话，会剔除大量的中文博客。

而且，声明自己的博客是中文博客，根据 W3 的 [ISO 639-3 and Macro Languages](https://www.w3.org/International/articles/bcp47/#macro) 标准在 HTML 中声明会比较合适。

**Comment by linlinzzo** [comment]
> 中文博客并不是每个都在 HTML 中声明自己的博客是中文，即在 HTML 中的标签内写上 lang="zh"。如果按照这个标准来执行的话，会剔除大量的中文博客。

我们其实并不会片面只看 html lang，你也可以在我们的博客列表中看到很多 lang 错填的博客。我们的想法是收录中文博客，不是国内的中文博客，更不是讨***喜欢的中文博客，所以剔除中文博客的现象目前在我们项目已被避免。

**Comment by linlinzzo** [comment]
我们的博客列表在线地址是 https://zhblogs.ohyee.cc/?tab=blog_list&page=1&tags=&search= 。

**Comment by MYXXTS** [comment]
关于合并，我的意见是可行的，多项目同时维护，节省人工，也节省时间。

**Comment by yzqzss** [comment]
![图片](https://user-images.githubusercontent.com/30341059/169682179-b5ccb139-fa13-4ed2-b20f-aa9e63136d26.png)

blog-daohang 那边数据库里可以加一个 key 吗？
可以叫做 saveweb_id 之类的，用于记录博客在我们这边的对应ID。

方便以后跟踪和去重数据；之后我们这边搞出API之后，还能直接对比我们两边的收录信息是否有差异。
