### ISSUE TITLE
请求移除博客

### ISSUE THREAD

**Issue by sevi418** [saveweb/rss-list#5]
您好，我是seviche.cc的所有者，我希望能将本博客从此计划中移除。

**Comment by yzqzss** [comment]
是只移除 saveweb/rss-list 还是 saveweb/review-2023 , https://search.saveweb.org 等等一并移除？

**Comment by sevi418** [comment]
麻烦一并移除吧，谢谢！

**Comment by yzqzss** [comment]
已移除。
search 的收录需要等待下一次全量索引才会移除。

**Comment by sevi418** [comment]
您好，请问丑搜是相关的项目嘛，为什么在这个issue之后还是收录了我的博文呢，请问这边方便删除一下嘛，而且这边博客已经失效了，删除可能会更好一些。

<img width="1090" alt="Image" src="https://github.com/user-attachments/assets/b4a504ce-c0bb-4db3-91b9-2478c43b4c4e" />

**Comment by yzqzss** [comment]
如果我说是删了之后，过了几个月又被加回来了，你信吗……

**Comment by yzqzss** [comment]
这次应该删干净了。

**Comment by sevi418** [comment]
谢谢！
