### ISSUE TITLE
这是没同步上游，还是没修改上次同步上游的时间？

### ISSUE THREAD

**Issue by HowieHz** [saveweb/rss-list#6]
![image](https://github.com/saveweb/rss-list/assets/94725606/9e100bc8-fa00-4649-a2d0-1384321edf09)
如图

**Comment by HowieHz** [comment]
@yzqzss

**Comment by yzqzss** [comment]
没修改时间，实际是同步到了 2023 年下旬。
这一两年没怎么维护 rss-list，就每半年发次 release 时会手工同步一下上游源。

**Comment by HowieHz** [comment]
> 没修改时间，实际是同步到了 2023 年下旬。 这一两年没怎么维护 rss-list，就每半年发次 release 时会手工同步一下上游源。

感谢回复，感谢维护
